versi贸n:  0.0 
sistema operativo:  linux 
archivos: 
  -  origen:  / 
    destino:  /home/ec2-ubuntu/techflare-backend 
ganchos: 
  ApplicationStop: 
    -  ubicaci贸n:  scripts/application_stop.sh 
      tiempo de espera:  300 
      runas:  ec2-ubuntu 
  BeforeInstall: 
    -  ubicaci贸n:  scripts/before_install.sh 
      tiempo de espera:  300 
      runas:  ec2-ubuntu 
  ApplicationStart: 
    -  ubicaci贸n:  scripts/application_start.sh 
      tiempo de espera:  300 
      runas:  ec2-ubuntu